### ISSUE TITLE
 cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by elliottucker-swrve** [pyToshka/docker-wazuh-agent#10]
it looks like an upstream change to one of the python packages has been made and the latest build (413c522ce26db43918124b1d4b1e9fc624046d846bf7729fbffd6c7c9394b4ec) doesn't run:

**Test** 
`docker run --rm **kennyopennix/wazuh-agent:latest

**Expected Behaviour**
Agent starts, but with maybe environment errors

**Actual Behaviour**
```
Traceback (most recent call last):
  File "/var/ossec/./register_agent.py", line 11, in <module>
    from flask import Flask
  File "/usr/local/lib/python3.9/dist-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/usr/local/lib/python3.9/dist-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.9/dist-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.9/dist-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.9/dist-packages/markupsafe/__init__.py)
```

I've pulled from here and tried to build with the Dockerfile but I'm getting the same issue.  Have tried with different version locks on requirements.txt but I'm not getting anywhere...seems there are multiple issue.

**Comment by pyToshka** [comment]
@elliottucker-swrve thank you for issue, i'm working on solution and improvements

**Comment by pyToshka** [comment]
fixed

**Comment by elliottucker-swrve** [comment]
thanks! much appreciated. works great
