### ISSUE TITLE
KeyError: 'data'

### ISSUE THREAD

**Issue by brickshandy** [pyToshka/docker-wazuh-agent#18]
Hi 
I meet issue when deploying wazuh agent as daemonset, and here the error from the pod

```
Traceback (most recent call last):
  File "/var/ossec/./register_agent.py", line 289, in <module>
    agent_id, agent_key = add_agent(node_name)
  File "/var/ossec/./register_agent.py", line 174, in add_agent
    status_code, response = wazuh_api(
  File "/var/ossec/./register_agent.py", line 91, in wazuh_api
    token = json.loads(response.content.decode())["data"]["token"]
KeyError: 'data'
```
can you help  me on this ?
thank you

**Comment by brickshandy** [comment]
hi @pyToshka thanks for your feedback, there was a typo when I create the secret file

thank you
