### ISSUE TITLE
Is Wazuh Agent Docker Image version 4.3.10 compatible with Wazuh Manager version 4.4.1?

### ISSUE THREAD

**Issue by SERG1U5** [pyToshka/docker-wazuh-agent#21]
Is Wazuh Agent Docker Image version 4.3.10 compatible with Wazuh Manager version 4.4.1?

**Comment by igadaaka** [comment]
I am getting this error when trying to run the agent agains API version `4.4.1`: 
```
{"timestamp": 1683551823.790013, "message": "Create Wazuh agent configuration for node lima-rancher-desktop"}
{"timestamp": 1683551823.796765, "message": "Configuration has been generated from template, starting Wazuh agent provisioning"}
Traceback (most recent call last):
  File "/var/ossec/./register_agent.py", line 289, in <module>
    agent_id, agent_key = add_agent(node_name)
  File "/var/ossec/./register_agent.py", line 174, in add_agent
    status_code, response = wazuh_api(
  File "/var/ossec/./register_agent.py", line 91, in wazuh_api
    token = json.loads(response.content.decode())["data"]["token"]
KeyError: 'data'
```
