### ISSUE TITLE
KeyError: Data message

### ISSUE THREAD

**Issue by trentnbauer** [pyToshka/docker-wazuh-agent#30]
```
Create Wazuh agent configuration for node basil | timestamp=1691043841.14798
Configuration has been generated from template, starting Wazuh agent provisioning | timestamp=1691043841.151348
Traceback (most recent call last):
  File "/var/ossec/./register_agent.py", line 289, in <module>
    agent_id, agent_key = add_agent(node_name)
  File "/var/ossec/./register_agent.py", line 174, in add_agent
    status_code, response = wazuh_api(
  File "/var/ossec/./register_agent.py", line 91, in wazuh_api
    token = json.loads(response.content.decode())["data"]["token"]
KeyError: 'data'
```

Compose  file:
```
version: "3.2"

services:
  wazuh-agent:
    image: kennyopennix/wazuh-agent:latest
    volumes:
      - /etc/os-release:/etc/os-release
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/rootfs:ro
      - ossec:/var/ossec
    network_mode: host
    environment:
      - JOIN_MANAGER_MASTER_HOST=server.dns.name
      - JOIN_MANAGER_WORKER_HOST=server.dns.name
      - JOIN_MANAGER_PASSWORD=web admin password
      - JOIN_MANAGER_USER=web admin username
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true

volumes:
  ossec:
```

**Comment by trentnbauer** [comment]
G'day mate
I'm using the admin credentials I use to log into the wazuh web ui.
Are these the right credentials?

**Comment by trentnbauer** [comment]
Oh whoops - got that working. Thats heaps mate!
